---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: rds-bindable
  namespace: default
spec:
  serviceAccountName: rds-resources-reader
  inputResources:
  - name: rds
    ref:
      apiVersion: rds.services.k8s.aws/v1alpha1
      kind: DBInstance
      name: rds-psql-1
  - name: creds
    ref:
      apiVersion: v1
      kind: Secret
      name: "$(.rds.spec.masterUserPassword.name)"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rds-postgres
        app.kubernetes.io/instance: "$(.rds.metadata.name)"
        services.apps.tanzu.vmware.com/class: rds-postgres
    type: postgresql
    stringData:
      type: postgresql
      port: "$(.rds.status.endpoint.port)"
      database: "$(.rds.spec.dbName)"
      host: "$(.rds.status.endpoint.address)"
      username: "$(.rds.spec.masterUsername)"
    data:
      password: "$(.creds.data.password)"

#! RBAC required for SecretTemplate to create bindable Secret.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rds-resources-reader
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rds-resources-reading
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  resourceNames:
  - rds-psql-password
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbinstances
  verbs:
  - get
  - list
  - watch
  resourceNames:
  - rds-psql-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rds-resources-reader-to-read
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rds-resources-reading
subjects:
- kind: ServiceAccount
  name: rds-resources-reader
  namespace: default
