---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: rds-bindable
  namespace: default
spec:
  serviceAccountName: rds-resources-reader
  inputResources:
  - name: rds
    ref:
      apiVersion: rds.services.k8s.aws/v1alpha1
      kind: DBInstance
      name: rds-psql-1
  - name: creds
    ref:
      apiVersion: v1
      kind: Secret
      name: "$(.rds.spec.masterUserPassword.name)"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rds-postgres
        app.kubernetes.io/instance: "$(.rds.metadata.name)"
        services.apps.tanzu.vmware.com/class: rds-postgres
    type: postgresql
    stringData:
      type: postgresql
      port: "$(.rds.status.endpoint.port)"
      database: "$(.rds.spec.dbName)"
      host: "$(.rds.status.endpoint.address)"
      username: "$(.rds.spec.masterUsername)"
    data:
      password: "$(.creds.data.password)"
