---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rmq-instance

---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rmq-user
spec:
  rabbitmqClusterReference:
    name: rmq-instance
  importCredentialsSecret:
    name: rmq-user-credentials

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: rmq-user-credentials
spec:
  length: 64
  secretTemplate:
    type: Opaque
    stringData:
      password: $(value)
      username: rmq-instance
      
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rmq-perms
spec:
  vhost: "/"
  user: rmq-instance
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name:  rmq-instance