---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rmq-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rmq-reader
rules:
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  - users
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rmq-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rmq-reader
subjects:
- kind: ServiceAccount
  name: rmq-reader