
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: rmq-user-bindable
spec:
  serviceAccountName: rmq-reader
  inputResources:
  - name: user
    ref:
      apiVersion: rabbitmq.com/v1beta1
      kind: User
      name: rmq-user
  - name: rmq
    ref:
      apiVersion: rabbitmq.com/v1beta1
      kind: RabbitmqCluster
      name: $(.user.spec.rabbitmqClusterReference.name)
  - name: service
    ref:
      apiVersion: v1
      kind: Service
      name: $(.rmq.status.defaultUser.serviceReference.name)
  - name: creds
    ref:
      apiVersion: v1
      kind: Secret
      name: $(.user.metadata.name)-user-credentials 
  template:
    type: rabbitmq
    stringData:
      type: rabbitmq
      port: $(.service.spec.ports[?(@.name=="amqp")].port)
      host: $(.service.spec.clusterIP)
      username: $(.user.status.username)   
    data:        
      password: $(.creds.data.password)
